package_assets:         off          # (on, off, always)
embed_images:           on          # (on, off, datauri)
template_function:      _.template  # (defaults to the built-in micro-templating)
package_path:           assets    # (defaults to assets)
compress_assets:        on
javascript_compressor:  closure     # (yui, closure)
 
javascripts:
  workspace:
    - public/javascripts/jquery.cookie.js
    - public/javascripts/jquery.url.js
    - public/javascripts/jquery.autocomplete.pack.js
    - public/javascripts/jquery.placeholder.js
    - public/javascripts/application.js
    - public/javascripts/jquery.imageViewerWebsite.js
    - public/javascripts/facebox.js
    - public/javascripts/jquery.livequery.js
    - public/javascripts/jquery.jplayer.min.js
    - public/javascripts/flowplayer-3.1.4.min.js
    - public/javascripts/jquery.combobox.js
    - public/javascripts/lightbox.js
  admin:
    - public/javascripts/ui.core.js
    - public/javascripts/ui.datepicker.js
    - public/javascripts/admin.js
  player:
    - public/javascripts/player.js
    - public/javascripts/jquery-ui-1.8.23.custom.min.js
  # droppy:
  #    - public/assets/jquery.droppy.js
 
stylesheets:
  workspace:
    - public/stylesheets/facebox.css
    - public/stylesheets/reset.css
    - public/stylesheets/shared.css
    - public/stylesheets/lightbox.css
  # droppy:
  #   - public/assets/droppy-datauri.css
  home:
    - public/stylesheets/home.css
  player:
    - public/stylesheets/player.css
  admin:
    - public/stylesheets/admin.css
    - public/stylesheets/jquery.css
    - public/stylesheets/jquery.autocomplete.css
  print:
    - public/stylesheets/print.css